# Generated by Django 4.1.5 on 2023-01-31 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='accounts.categories'),
        ),
    ]
