# Generated by Django 4.1.5 on 2023-02-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clients_user_alter_categories_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Types',
        ),
    ]
