# Generated by Django 4.1.5 on 2023-02-03 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_post_category_categories_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='accounts.categories'),
        ),
    ]
