# Generated by Django 4.1.5 on 2023-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_list_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='category',
        ),
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.ManyToManyField(related_name='list', to='accounts.categories'),
        ),
    ]
