# Generated by Django 4.1.5 on 2023-02-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_list_category_list_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='category',
        ),
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='accounts.categories'),
        ),
    ]
