# Generated by Django 4.1.5 on 2023-02-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_list_count_list_created_dt_list_num_motor_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
