# Generated by Django 4.1.5 on 2023-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
