# Generated by Django 4.1.5 on 2023-02-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_clients_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
