# Generated by Django 4.1.5 on 2023-02-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
